### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by vbhanuc87** [creactiviti/graffiti#1]
More of a question than an issue. First of all, great work and I loved the concepts. But, what are the real world use cases when I can use this ? Is it more like a graphql implementation using java and SB ? Apologies if I am too naive.

**Comment by runabol** [comment]
Let me know if this answers your question: 

https://github.com/creactiviti/graffiti#why-god-why

**Comment by bvipparla** [comment]
Awesome. Thanks much and really appreciate the efforts. Great work. Makes sense now with the why-god-why section.

**Comment by vbhanuc87** [comment]
Thats from my other id. You can delete the earlier comment if needed

Awesome. Thanks much and really appreciate the efforts. Great work. Makes sense now with the why-god-why section.
